# Generated by Django 2.1.5 on 2019-02-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('student_type', models.CharField(choices=[('0', 'candidate'), ('1', 'voter')], max_length=1)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_vote_system.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_user_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_vote_system.User')),
            ],
        ),
    ]
